from tkinter import *
note=Tk()
menu=Menu(note)
note.config(menu=menu)
filemenu=Menu(menu)
menu.add_cascade(label='file',menu=filemenu)
filemenu.add_command(label='new')
filemenu.add_command(label='open')
filemenu.add_command(label='save')
filemenu.add_command(label='save as')
filemenu.add_command(label='page set up')
filemenu.add_command(label='print')
filemenu.add_command(label='close',command=quit)
editmenu=Menu(menu)
menu.add_cascade(label='edit',menu=editmenu)
editmenu.add_command(label='cut')
editmenu.add_command(label='copy')
editmenu.add_command(label='paste')
editmenu.add_command(label='delete')
editmenu.add_command(label='find next')
editmenu.add_command(label='find previous')
editmenu.add_command(label='replace')
formatmenu=Menu(menu)
menu.add_cascade(label='format',menu=formatmenu)
formatmenu.add_command(label='word wrap')
formatmenu.add_command(label='font')
mainloop()
